- name: messagebus user is added to the root group
  user:
    name: messagebus
    group: root
  register: user_result
  tags: [postgresql]

- name: sameersbn-postgresql:9.6-2
  docker_container:
    privileged: yes
    env:
      DB_USER: suhua
      DB_PASS: suhua@DB 
      DB_NAME: itms
    image: sameersbn/postgresql:9.6-2
    name: postgresql
    ports: 
    - "49160:22"
    - "49161:80"
    - "5432:5432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/postgresql:/var/lib/postgresql
  tags: [postgresql]
 
